version: '2'
services:
    postgres:
        image: 'psql:latest'
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=12345
          - PGUSER=postgres
          - PGHOST=postgres
          - PGDATABASE=postgres
          - PGPASSWORD=12345
          - PGPORT=5432
        logging:
          options:
            max-size: 10m
            max-file: "3"
        #ports:
        #  - '5000-5010:5432'
        expose:
          - "5000"
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/world.sql:/docker-entrypoint-initdb.d/world.sql
    nginx:
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - postgres
        ports:
           - "4000:4000"
