CREATE DATABASE rotators OWNER postgres;

CREATE USER Dotty WITH PASSWORD '1XbRp7YxWKA1e9';
CREATE USER Fiber WITH PASSWORD 'bigOtiUvdmi3mz';

GRANT ALL PRIVILEGES ON DATABASE rotators TO Dotty, Fiber;


CREATE DATABASE hydraulics OWNER postgres;
CREATE USER Terra WITH PASSWORD 'dxoBRdVHkJcyBT';
CREATE USER Azerty WITH PASSWORD 'fcbR4A8E1JN89I';

GRANT ALL PRIVILEGES ON DATABASE hydraulics TO Terra, Azerty;

CREATE DATABASE jumpers OWNER postgres; 
CREATE USER Efk WITH PASSWORD 'OPDQyMu3HJcjyr';
CREATE USER Spark WITH PASSWORD 'ryq4olmwB9hsqV';

GRANT ALL PRIVILEGES ON DATABASE jumpers TO Efk, Spark;

CREATE USER Alpha WITH PASSWORD 'EY2cT39n5RS0eR';

GRANT CONNECT ON DATABASE rotators, hydraulics, jumpers TO Alpha;
